### PR TITLE
We don't really need core utils.

### PR DESCRIPTION
**Pull request by wibisono**
Managed to install this in xenial (vagrant).

### CODE REVIEW

**Comment by lolepezy** [comment]
> curl - for the upload-ta script (at least as recommended)
Indeed! That's a good catch.

> * which
Isn't "which" a built-in shell command?

**Comment by ties** [comment]
> > * which
> >   Isn't "which" a built-in shell command?

I tested it in a minimal environment. It appears to be included there (as well as `/bin/sh`).

**Comment by wibisono** [comment]
Curl added, debianutils seems okay to leave out.

**Comment by ties** [comment]
@wibisono I think my proposed change wasn't a good idea. Merged 👍

**Pull request merged**
